---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 'https://api.stackbit.com/project/5d3b781889d0f4001391114b/webhook/forestry'
sections:
  - type: document
    label: Global Site Config
    path: site-metadata.json
    templates:
      - config
  - type: document
    label: Author
    path: src/data/author.json
    templates:
      - author
  - type: document
    label: Header
    path: src/data/header.yml
    templates:
      - header
  - type: document
    label: Footer
    path: src/data/footer.yml
    templates:
      - footer
  - type: document
    label: Social Links
    path: src/data/social.json
    templates:
      - social
  - type: document
    label: Documentation Sections
    path: src/data/doc_sections.yml
    templates:
      - doc_sections
  - type: directory
    path: src/pages
    match: '**/*'
    exclude: '{index.md,blog/index.md,overview.md,showcase.md}'
    label: Documentation Pagess
    create: all
    templates:
      - docs
  - type: document
    label: Home
    path: src/pages/index.md
    templates:
      - home
  - type: document
    label: Blog
    path: src/pages/blog/index.md
    templates:
      - blog
  - type: document
    label: Overview
    path: src/pages/overview.md
    templates:
      - overview
  - type: document
    label: Showcase
    path: src/pages/showcase.md
    templates:
      - showcase
  - type: directory
    path: src/pages
    match: '**/*'
    exclude: '{posts/**,index.md,blog/index.md,overview.md,showcase.md}'
    label: Pages
    create: all
    templates:
      - page
  - type: directory
    path: src/pages/posts
    match: '**/*'
    label: Posts
    create: all
    templates:
      - post
upload_dir: static/images
public_path: /images
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
